os:
    - linux
    - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode7.3
install:
    - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/02090c7ede5a637b76e6df1710e83cd0bbe7dcdf/swiftenv-install.sh)"
script:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo xcode-select -s /Applications/Xcode.app/ ; fi
    # Build Vapor
    - swift build --configuration debug
    - swift build --configuration release
    # Test Vapor
    - swift test
